# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-430e2b02-5f47-43f3-9ae5-1e90a4a91952";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-430e2b02-5f47-43f3-9ae5-1e90a4a91952".device = "/dev/disk/by-uuid/430e2b02-5f47-43f3-9ae5-1e90a4a91952";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/477E-585D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a5feba67-fcf2-4840-bb72-683c5f436f96"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
