format = """\
$container\
$username\
$os\
$git_branch\
( at $directory )\
$cmd_duration\
( via $python$conda$nodejs$c$rust$java )
"""

add_newline = false

palette = "normal"

[palettes.normal] # - Universal Compromise Palette
# Works on both, but looks most native on Latte.
arrow      = "#a6a6a6"  # Latte Subtext0
os         = "#179299"  # Latte Teal
os_admin   = "#df8e1d"  # Latte Yellow
directory  = "#1e66f5"  # Latte Blue
time       = "#04a5e5"  # Latte Sky
node       = "#40a02b"  # Latte Green
git        = "#fe640b"  # Latte Peach
git_status = "#ea76cb"  # Latte Pink
python     = "#df8e1d"  # Latte Yellow
conda      = "#40a02b"  # Latte Green
java       = "#d20f39"  # Latte Red
rust       = "#e64553"  # Latte Maroon
clang      = "#8839ef"  # Latte Mauve
duration   = "#d20f39"  # Latte Red
text_color = "#4c4f69"  # Latte Text
text_light = "#6c6f85"  # Latte Subtext1

[username]
style_user = 'bold os'
style_root = 'bold os_admin'
format = '[$user]($style) '
disabled = false
show_always = true

[container]
format = '[$symbol \[$name\]]($style): '

[os]
format = "[$symbol$name]($style) "
style = "bold os"
disabled = false

[os.symbols]
Alpine = " "
Arch = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
openSUSE = " "
Pop = " "
SUSE = " "
Ubuntu = " "
Windows = " "

[character]
success_symbol = "[󰍟](fg:arrow)"
error_symbol = "[󰍟](fg:red)"

[directory]
format = "[$path](bold $style)[$read_only]($read_only_style)"
truncation_length = 2
style = "fg:directory"
read_only_style = "fg:directory"
before_repo_root_style = "fg:directory"
truncation_symbol = "…/"
truncate_to_repo = true
read_only =" " 

[cmd_duration]
format = "took [ $duration]($style) "
style = "bold fg:duration"
min_time = 500

[git_branch]
format = "on [$symbol$branch]($style) "
style = "bold fg:git"
symbol = " "

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = "fg:text_color bg:git"
disabled = false

# --- Language Tooling ---
# The modules are grouped in the main format string.
# The internal padding '[ $symbol... ]' ensures they don't mash together.

[nodejs]
format = "[ $symbol$version ]($style)"
style = "bg:node fg:text_light"
symbol = " "
version_format = "${raw}"
disabled = false

[python]
format = '[ $symbol${pyenv_prefix}(${version})( \($virtualenv\)) ]($style)'
symbol = " "
version_format = "${raw}"
style = "bg:python fg:text_light"
disabled = false

[conda]
format = "[ $symbol$environment ]($style)"
style = "bg:conda fg:text_light"
ignore_base = false
symbol = " "
disabled = false

[java]
format = "[ $symbol$version ]($style)"
style = "bg:java fg:text_light"
version_format = "${raw}"
symbol = " "
disabled = false

[c]
format = "[ $symbol($version(-$name)) ]($style)"
style = "bg:clang fg:text_light"
symbol = " "
version_format = "${raw}"
disabled = false

[rust]
format ="[ $symbol$version ]($style)"
style = "bg:rust fg:text_light"
symbol = " "
version_format = "${raw}"
disabled = false